<a href="https://colab.research.google.com/github/LAUROJAS3/Seminario_RN/blob/main/LRC_P07_Matrix_%26_Mult.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Multiplicacion de Matrices

En este laboratorio, se utilizaran las funciones de `NumPy` para realizar la multiplicacion de matrices y se vera como se puede aplicar en las aplicaciones de aprendizaje automatico.

#Tabla de Contenido
- [ 1 - Definicion de la Multiplicacion de Matrices](#1)
- [ 2 - Multiplocacion de Matrices con Python](#2)
- [ 3 - Convencion de Matrices y Difusion(Broadcasting)](#3)


# Paquetes

Carga el paquete `NumPy` para acceder a sus funciones.

In [ ]:
import numpy as np

<a name='2'></a>
## 1 - Definicion de la Multiplicacion de Matrices

Si $A$ es una matriz de dimensiones $m \times n$ y $B$ es una matriz de dimensiones $n \times p$, el producto matricial $C = AB$ (denotado sin signos de multiplicación ni puntos) se define como la matriz de dimensiones $m \times p$ tal que:


$c_{ij}=a_{i1}b_{1j}+a_{i2}b_{2j}+ ... +a_{in}b_{nj}=\sum_{k=1}^{n} a_{ik}b_{kj}, \tag{4}$


donde $a_{ik}$ son los elementos de la matriz $A$, $b_{kj}$ son los elementos de la matriz $B$, e $i = 1, ..., m$, $k=1, ... , n$, $j = 1, ..., p$. En otras palabras, $c_{ij}$ es el producto punto de la $i$-esima fila de $A$ y la $j$-esima columna de $B$.

<a name='2'></a>
## 2 - Multiplicacion de Matrices con Python

Al igual que con el producto punto, hay varias formas de realizar la multiplicacioon de matrices en Python. Como se discutió en el laboratorio anterior, los cálculos son más eficientes en la forma vectorizada. Analicemos las funciones mas comúnmente utilizadas en la forma vectorizada. Primero, definamos dos matrices:

In [ ]:
A=np.array([[4,9,9],[9,1,6],[9,2,3]])
print("Matrix A (3 x 3):\n",A)

B=np.array([[2,2],[5,7],[4,4]])
print("Matrix B (3 x 3):\n",B)

Matrix A (3 x 3):
 [[4 9 9]
 [9 1 6]
 [9 2 3]]
Matrix B (3 x 3):
 [[2 2]
 [5 7]
 [4 4]]


Puedes multiplicar las matrices $A$ y $B$ utilizando la función `np.matmul()` del paquete `NumPy`:

In [ ]:
np.matmul(A,B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

Esto producirá una matriz de $3 \times 2$ como un `np.array`. El operador `@` de Python también funcionará aquí, dando el mismo resultado:

In [ ]:
A@B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

<a name='3'></a>
## 3 - Convención de Matrices y Difusión (Broadcasting)

Matemáticamente, la multiplicación de matrices está definida solo si el número de columnas de la matriz $A$ es igual al número de filas de la matriz $B$ (puedes revisar nuevamente la definición en la sección [1](#1) y ver que, de lo contrario, los productos punto entre filas y columnas no estarán definidos).

Por lo tanto, en el ejemplo anterior ([2](#2)), cambiar el orden de las matrices al realizar la multiplicación $BA$ no funcionará, ya que la regla mencionada anteriormente ya no se cumple. Puedes comprobarlo ejecutando las celdas a continuación; ambas darán errores.

In [ ]:
try:
  np.matmul(B,A)

except ValueError as err:
  print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [ ]:
try:
  B@A

except ValueError as err:
  print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


Por lo tanto, al utilizar la multiplicación de matrices, debes tener mucho cuidado con las dimensiones: el número de columnas en la primera matriz debe coincidir con el número de filas en la segunda matriz. Esto es muy importante para tu comprensión futura de las Redes Neuronales y cómo funcionan.

Sin embargo, para multiplicar vectores, `NumPy` tiene un atajo. Puedes definir dos vectores $x$ e $y$ del mismo tamaño (que se pueden entender como dos matrices $3 \times 1$). Si verificas la forma del vector $x$, puedes ver que:

In [ ]:
x=np.array([1,-2,-5])

y=np.array([4,3,-1])

print("Shape of Vector X:",x.shape)
print("Number of Dimensions of Vector X:",x.ndim)
print("Shape of Vector X, Reshaped to a Matrix",x.reshape((3,1)).shape)
print("Number of Dimensions of Vector X, Reshaped to a Matrix:",x.reshape((3,1)).ndim)

Shape of Vector X: (3,)
Number of Dimensions of Vector X: 1
Shape of Vector X, Reshaped to a Matrix (3, 1)
Number of Dimensions of Vector X, Reshaped to a Matrix: 2


Siguiendo la convención de matrices, la multiplicación de matrices $3 \times 1$ y $3 \times 1$ no está definida. Para la multiplicación de matrices, esperarías un error en la siguiente celda, pero comprobemos la salida:

In [ ]:
np.matmul(x,y)

np.int64(3)

Puedes ver que no hay error y que el resultado es, de hecho, un producto punto $x \cdot y\,$. Así que, el vector $x$ se transpuso automáticamente al vector $1 \times 3$ y se calculó la multiplicación de matrices $x^Ty$. Aunque esto es muy conveniente, debes tener en cuenta esta funcionalidad en Python y prestar atención para no usarla de manera incorrecta. La siguiente celda devolverá un error:

In [ ]:
try:
  np.matmul(x.reshape((3,1)), y.reshape((3,1)))

except ValueError as err:
  print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)


Puede que te estés preguntando: ¿la función `np.dot()` también funciona para la multiplicación de matrices? Probémoslo:

In [ ]:
np.dot(A,B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

¡Sí, funciona! Lo que realmente sucede es lo que se llama **difusión** en Python: `NumPy` difunde esta operación de producto punto a todas las filas y columnas, obteniendo la matriz de producto resultante. La difusión también funciona en otros casos, por ejemplo:

In [ ]:
A-2

array([[ 2,  7,  7],
       [ 7, -1,  4],
       [ 7,  0,  1]])

Matemáticamente, la resta de la matriz $3 \times 3$ $A$ y un escalar no está definida, pero Python difunde el escalar, creando un `np.array` de $3 \times 3$ y realizando la resta elemento por elemento. Un ejemplo práctico de multiplicación de matrices se puede ver en un modelo de regresión lineal. ¡Lo implementarás en la tarea de esta semana!